services:
  - type: web
    name: arabic-vocabulary-backend
    runtime: java
    rootDir: vocabulary
    plan: free
    buildCommand: chmod +x ./mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER  
        sync: false
      - key: DB_PASS
        sync: false
