services:
  - type: web
    name: arabic-vocabulary-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER  
        sync: false
      - key: DB_PASS
        sync: false
